spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital
spring.datasource.username=Zhuanz1
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

encryption.secret-key=HaZMSGmx3Qdia6K27YNAtXcpBoh6MH2t5ozsb344Ebo=
GooglePassword=yjhw grsk tgdv shaj
GoogleEmail=courageobunike@gmail.com
jwt.secret=ThisIsAVeryLongSecretKeyThatShouldBeAtLeast256BitsLongForSecurity
jwt.expiration=86400000
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method